CRITICAL - 2022-01-12 08:37:52 --> Undefined array key 0
#0 C:\xampp\htdocs\CRUD\app\Controllers\Home.php(140): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 140)
#1 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(825): App\Controllers\Home->deposita()
#2 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-01-12 08:43:35 --> Undefined array key 0
#0 C:\xampp\htdocs\CRUD\app\Controllers\Home.php(140): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 140)
#1 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(825): App\Controllers\Home->deposita()
#2 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-01-12 08:54:50 --> Undefined array key 0
#0 C:\xampp\htdocs\CRUD\app\Controllers\Home.php(127): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 127)
#1 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(825): App\Controllers\Home->deposita()
#2 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2022-01-12 08:57:29 --> Lock wait timeout exceeded; try restarting transaction
CRITICAL - 2022-01-12 08:57:29 --> Lock wait timeout exceeded; try restarting transaction
#0 C:\xampp\htdocs\CRUD\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `conta` ...', 0)
#1 C:\xampp\htdocs\CRUD\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `conta` ...')
#2 C:\xampp\htdocs\CRUD\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `conta` ...')
#3 C:\xampp\htdocs\CRUD\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE `conta` ...', Array, false)
#4 C:\xampp\htdocs\CRUD\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\CRUD\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\CRUD\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\CRUD\app\Controllers\Home.php(139): CodeIgniter\Model->update('1', Array)
#8 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(825): App\Controllers\Home->deposita()
#9 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-01-12 08:59:10 --> MySQL server has gone away
CRITICAL - 2022-01-12 08:59:10 --> MySQL server has gone away
#0 C:\xampp\htdocs\CRUD\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `conta` ...', 0)
#1 C:\xampp\htdocs\CRUD\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `conta` ...')
#2 C:\xampp\htdocs\CRUD\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `conta` ...')
#3 C:\xampp\htdocs\CRUD\system\Database\BaseBuilder.php(1913): CodeIgniter\Database\BaseConnection->query('UPDATE `conta` ...', Array, false)
#4 C:\xampp\htdocs\CRUD\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\CRUD\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\CRUD\system\Model.php(651): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\CRUD\app\Controllers\Home.php(127): CodeIgniter\Model->update('1', Array)
#8 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(825): App\Controllers\Home->deposita()
#9 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-01-12 08:59:10 --> Maximum execution time of 120 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-12 08:59:10 --> Maximum execution time of 120 seconds exceeded
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-12 09:31:09 --> Undefined array key 0
#0 C:\xampp\htdocs\CRUD\app\Controllers\Home.php(139): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 139)
#1 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(825): App\Controllers\Home->deposita()
#2 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#3 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2022-01-12 09:31:55 --> Table 'carbanco.transação' doesn't exist
CRITICAL - 2022-01-12 09:31:55 --> Table 'carbanco.transação' doesn't exist
#0 C:\xampp\htdocs\CRUD\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `tr...', 0)
#1 C:\xampp\htdocs\CRUD\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tr...')
#2 C:\xampp\htdocs\CRUD\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tr...')
#3 C:\xampp\htdocs\CRUD\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tr...', Array, false)
#4 C:\xampp\htdocs\CRUD\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\CRUD\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\CRUD\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\CRUD\app\Controllers\Home.php(155): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(825): App\Controllers\Home->deposita()
#9 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#10 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-01-12 09:35:32 --> Call to undefined function App\Controllers\NOW()
#0 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(825): App\Controllers\Home->deposita()
#1 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#2 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2022-01-12 09:53:50 --> Unknown column 'Conta_id' in 'where clause'
CRITICAL - 2022-01-12 09:53:50 --> Unknown column 'Conta_id' in 'where clause'
#0 C:\xampp\htdocs\CRUD\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\CRUD\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\CRUD\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\CRUD\system\Database\BaseBuilder.php(1588): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CRUD\app\Controllers\Home.php(75): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#5 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(825): App\Controllers\Home->exibirSaldo()
#6 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-01-12 15:24:08 --> Undefined variable $conta
#0 C:\xampp\htdocs\CRUD\app\Views\exibirSaldo.php(58): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 58)
#1 C:\xampp\htdocs\CRUD\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\CRUD\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\CRUD\system\Common.php(1089): CodeIgniter\View\View->render('exibirSaldo', Array, true)
#4 C:\xampp\htdocs\CRUD\app\Controllers\Home.php(82): view('exibirSaldo', Array)
#5 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(825): App\Controllers\Home->exibirSaldo()
#6 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\CRUD\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CRUD\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
